# GitHub Actions workflow for building and deploying the AIBridge React app

name: Deploy AIBridge App

on:
  push:
    branches:
      - master # Or 'main' depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Specify the pnpm version used in your project

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Deploy to Server (Placeholder - Requires Configuration)
        # This step is a placeholder. You need to replace it with your actual deployment method.
        # Example using SCP (Secure Copy Protocol) via SSH:
        # Requires secrets: SSH_PRIVATE_KEY, SERVER_USER, SERVER_HOST, TARGET_PATH
        # Configure these secrets in your GitHub repository settings: Settings > Secrets and variables > Actions
        run: |
          echo "Deploying build output..."
          # Example using rsync:
          # mkdir -p ~/.ssh
          # echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          # rsync -avz --delete ./dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.TARGET_PATH }}/aibridge/
          echo "Deployment step needs to be configured with your server details and secrets."
          echo "Target path should be the webroot for ahmdgawad.zapto.org/aibridge/"
          echo "Please replace this placeholder with your actual deployment script (e.g., using scp, rsync, ftp)."
        # Example using a dedicated deployment action (like appleboy/scp-action or appleboy/ssh-action):
        # uses: appleboy/scp-action@master
        # with:
        #   host: ${{ secrets.SERVER_HOST }}
        #   username: ${{ secrets.SERVER_USER }}
        #   key: ${{ secrets.SSH_PRIVATE_KEY }}
        #   port: 22 # Default is 22
        #   source: "dist/*"
        #   target: "${{ secrets.TARGET_PATH }}/aibridge/"

