# GitHub Actions workflow for building and deploying the AIBridge React app to GitHub Pages

name: Deploy AIBridge App to GitHub Pages

on:
  push:
    branches:
      - master # Or 'main' depending on your default branch

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Specify the pnpm version used in your project

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        # The base path was set to '.' in vite.config.ts for relative asset paths
        run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'dist' directory (Vite's default build output folder)
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

